# Generated by Django 4.2.3 on 2023-09-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('U_id', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.TextField(max_length=100)),
                ('Email', models.EmailField(max_length=60)),
                ('Contact', models.BigIntegerField()),
                ('Address', models.TextField(max_length=200)),
                ('Account_Type', models.TextField(max_length=20)),
                ('Partial_Amount', models.IntegerField()),
                ('Sign_Image', models.FileField(upload_to='sign_images')),
                ('Otp', models.IntegerField()),
            ],
            options={
                'db_table': 'userdetails1',
            },
        ),
    ]
