# Generated by Django 4.2.3 on 2023-09-03 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeDetails',
            fields=[
                ('C_id', models.AutoField(primary_key=True, serialize=False)),
                ('CName', models.TextField(max_length=100)),
                ('CAName', models.TextField()),
                ('CNumber', models.BigIntegerField(max_length=60)),
                ('CDAmount', models.BigIntegerField(max_length=30)),
                ('CSignImg', models.FileField(upload_to='cheque_images')),
                ('UserForegin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.userdetails')),
            ],
            options={
                'db_table': 'cheque_details1',
            },
        ),
    ]
