# Generated by Django 4.2.3 on 2023-09-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_chequedetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chequedetails',
            name='CAName',
        ),
        migrations.RemoveField(
            model_name='chequedetails',
            name='CDAmount',
        ),
        migrations.RemoveField(
            model_name='chequedetails',
            name='CName',
        ),
        migrations.RemoveField(
            model_name='chequedetails',
            name='CNumber',
        ),
        migrations.AddField(
            model_name='chequedetails',
            name='AccontNum',
            field=models.BigIntegerField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='chequedetails',
            name='DigitAmount',
            field=models.BigIntegerField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='chequedetails',
            name='ToName',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chequedetails',
            name='WordAmount',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
