# Generated by Django 4.2.3 on 2023-09-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_remove_chequedetails_caname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequedetails',
            name='AccontNum',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chequedetails',
            name='DigitAmount',
            field=models.BigIntegerField(null=True),
        ),
    ]
