# Generated by Django 4.2.3 on 2023-09-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_chequedetails_accontnum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequedetails',
            name='Cheque_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
