# Generated by Django 4.2.3 on 2023-09-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_chequedetails_cheque_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequedetails',
            name='CSignImg',
            field=models.TextField(null=True),
        ),
    ]
