# Generated by Django 4.2.3 on 2023-09-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_alter_chequedetails_csignimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequedetails',
            name='Status',
            field=models.TextField(null=True),
        ),
    ]
