# Generated by Django 4.2.3 on 2023-09-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_chequedetails_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='Otp',
            field=models.IntegerField(null=True),
        ),
    ]
