# Generated by Django 4.2.3 on 2023-09-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_alter_userdetails_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='Account_Number',
            field=models.BigIntegerField(null=True),
        ),
    ]
