# Generated by Django 4.2.1 on 2023-12-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_capturedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='Tries',
            field=models.IntegerField(default=0),
        ),
    ]
