# Generated by Django 4.2.3 on 2023-07-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=15, null=True)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
