# Generated by Django 4.2.3 on 2023-07-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_File',
            fields=[
                ('Video_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Video', models.FileField(upload_to='videos/')),
            ],
            options={
                'db_table': 'upload_video',
            },
        ),
    ]
